import React from "react"
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer"

// ── Colors ──
const colors = {
  black: "#000000",
  darkGray: "#333333",
  gray: "#666666",
  lightGray: "#e5e5e5",
  white: "#ffffff",
  headerBg: "#1e3a5f",
  accentBlue: "#a0c4e8",
  sectionBg: "#f0f4f8",
  fieldBg: "#fafafa",
  noticeBg: "#fff7ed",
  noticeBorder: "#fed7aa",
  noticeText: "#9a3412",
  badgeBg: "#e0e7ff",
  badgeText: "#3730a3",
  severityLow: "#16a34a",
  severityMedium: "#ca8a04",
  severityHigh: "#ea580c",
  severityCritical: "#dc2626",
}

const s = StyleSheet.create({
  page: { padding: 40, paddingBottom: 60, fontFamily: "Helvetica", fontSize: 9, color: colors.darkGray },
  footer: { position: "absolute", bottom: 20, left: 40, right: 40, fontSize: 7, color: colors.gray, flexDirection: "row", justifyContent: "space-between" },

  // Header
  headerBar: { backgroundColor: colors.headerBg, padding: 16, marginBottom: 16 },
  headerTitle: { fontSize: 16, fontWeight: "bold", color: colors.white, textAlign: "center" },
  headerSub: { fontSize: 10, color: colors.accentBlue, textAlign: "center", marginTop: 4 },

  // Cover
  coverMeta: { marginTop: 24, padding: 16, backgroundColor: colors.sectionBg, borderRadius: 4 },
  coverRow: { flexDirection: "row", marginBottom: 6 },
  coverLabel: { width: "35%", fontSize: 10, color: colors.gray },
  coverValue: { width: "65%", fontSize: 11, fontWeight: "bold" },

  // Form reference
  formRef: { fontSize: 8, color: colors.gray, textAlign: "right", marginBottom: 12 },

  // Section
  sectionTitle: { fontSize: 10, fontWeight: "bold", backgroundColor: colors.sectionBg, padding: 6, marginTop: 14, marginBottom: 6, borderBottom: `1px solid ${colors.lightGray}` },

  // Field row
  fieldRow: { flexDirection: "row", marginBottom: 4 },
  fieldLabel: { width: "40%", fontSize: 8, color: colors.gray, paddingVertical: 3 },
  fieldValue: { width: "60%", fontSize: 9, fontWeight: "bold", paddingVertical: 3, borderBottom: `1px solid ${colors.lightGray}` },
  fieldFull: { marginBottom: 4 },
  fieldFullLabel: { fontSize: 8, color: colors.gray, marginBottom: 2 },
  fieldFullValue: { fontSize: 9, padding: 6, backgroundColor: colors.fieldBg, border: `1px solid ${colors.lightGray}`, borderRadius: 2, minHeight: 30 },

  // Badge
  badge: { fontSize: 8, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 3, alignSelf: "flex-start" },

  // Table
  tableHeader: { flexDirection: "row", backgroundColor: colors.sectionBg, padding: 4, marginTop: 6 },
  tableHeaderCell: { fontSize: 8, fontWeight: "bold", color: colors.gray },
  tableRow: { flexDirection: "row", padding: 4, borderBottom: `1px solid ${colors.lightGray}` },
  tableCell: { fontSize: 8, color: colors.darkGray },

  // Witness card
  witnessCard: { marginBottom: 8, padding: 8, backgroundColor: colors.fieldBg, border: `1px solid ${colors.lightGray}`, borderRadius: 2 },
  witnessName: { fontSize: 9, fontWeight: "bold", marginBottom: 2 },
  witnessContact: { fontSize: 8, color: colors.gray, marginBottom: 4 },
  witnessStatement: { fontSize: 8, color: colors.darkGray },

  // Why chain
  whyRow: { flexDirection: "row", marginBottom: 3, paddingLeft: 8 },
  whyLabel: { fontSize: 8, fontWeight: "bold", color: colors.headerBg, width: 50 },
  whyText: { fontSize: 8, color: colors.darkGray, flex: 1 },

  // Signature block
  sigRow: { flexDirection: "row", gap: 20, marginTop: 20 },
  sigBlock: { flex: 1 },
  sigLine: { borderBottom: `1px solid ${colors.black}`, marginTop: 30, marginBottom: 4 },
  sigLabel: { fontSize: 8, color: colors.gray },

  // Notice
  notice: { marginTop: 16, padding: 8, backgroundColor: colors.noticeBg, border: `1px solid ${colors.noticeBorder}`, borderRadius: 2, fontSize: 8, color: colors.noticeText },

  // Confidential
  confidentialBanner: { textAlign: "center", fontSize: 8, fontWeight: "bold", color: colors.noticeText, marginTop: 6, letterSpacing: 2 },
})

// ── Helpers ──
function Field({ label, value }: { label: string; value: string | null | undefined }) {
  return (
    <View style={s.fieldRow}>
      <Text style={s.fieldLabel}>{label}</Text>
      <Text style={s.fieldValue}>{value || "\u2014"}</Text>
    </View>
  )
}

function FullField({ label, value }: { label: string; value: string | null | undefined }) {
  return (
    <View style={s.fieldFull}>
      <Text style={s.fieldFullLabel}>{label}</Text>
      <Text style={s.fieldFullValue}>{value || "\u2014"}</Text>
    </View>
  )
}

function Section({ title }: { title: string }) {
  return <Text style={s.sectionTitle}>{title}</Text>
}

function PageFooter({ reportDate, pageNum }: { reportDate: string; pageNum: string }) {
  return (
    <View style={s.footer} fixed>
      <Text>CONFIDENTIAL</Text>
      <Text>Generated by ConformEdge \u2014 {reportDate}</Text>
      <Text>{pageNum}</Text>
    </View>
  )
}

function severityColor(severity: string): string {
  switch (severity.toUpperCase()) {
    case "LOW": return colors.severityLow
    case "MEDIUM": return colors.severityMedium
    case "HIGH": return colors.severityHigh
    case "CRITICAL": return colors.severityCritical
    default: return colors.gray
  }
}

// ── Props ──

export interface InvestigationReportProps {
  // Organization
  orgName: string
  orgAddress?: string

  // Incident
  incidentRef: string
  title: string
  description?: string
  incidentType: string
  status: string
  severity: string
  incidentDate: string
  incidentTime?: string
  location?: string

  // Personnel
  injuredParty?: string
  victimOccupation?: string
  victimStaffNo?: string
  victimDepartment?: string
  victimIdNumber?: string
  victimNationality?: string
  victimContractor?: string
  immediateSupervisor?: string
  victimDateOfBirth?: string

  // Injury
  bodyPartInjured?: string
  natureOfInjury?: string
  treatmentType?: string
  treatingDoctor?: string
  hospitalClinic?: string
  lostDays?: string
  returnedToWork?: string
  returnedToWorkDate?: string

  // Investigation
  immediateAction?: string
  rootCause?: string
  rootCauseData?: {
    method: string
    category?: string
    whys?: Array<{ question: string; answer: string }>
    rootCause: string
    containmentAction?: string
  }
  contributingFactors?: string[]

  // Witnesses
  witnesses?: Array<{
    name: string
    contactNumber?: string
    email?: string
    statement?: string
  }>

  // Evidence
  evidence?: Array<{
    fileName: string
    fileType: string
    uploadedAt: string
    uploadedBy: string
  }>

  // CAPA
  linkedCapas?: Array<{
    title: string
    status: string
    type: string
    priority: string
  }>

  // Regulatory
  isReportable: boolean
  mhsaSection?: string
  reportingDeadline?: string
  statutoryReportedAt?: string

  // Cost
  estimatedCost?: string
  impactAreas?: string[]

  // Reporter
  reporterName: string
  investigatorName?: string
  reportDate: string
}

// ══════════════════════════════════════════════
// Investigation Report — Multi-page narrative PDF
// ══════════════════════════════════════════════

export function InvestigationReportForm(props: InvestigationReportProps) {
  return (
    <Document>
      {/* ── Page 1: Cover ── */}
      <Page size="A4" style={s.page}>
        <View style={s.headerBar}>
          <Text style={s.headerTitle}>Investigation Report</Text>
          <Text style={s.headerSub}>ConformEdge Incident Management</Text>
        </View>

        <View style={s.coverMeta}>
          <View style={s.coverRow}>
            <Text style={s.coverLabel}>Incident Reference</Text>
            <Text style={s.coverValue}>{props.incidentRef}</Text>
          </View>
          <View style={s.coverRow}>
            <Text style={s.coverLabel}>Incident Title</Text>
            <Text style={s.coverValue}>{props.title}</Text>
          </View>
          <View style={s.coverRow}>
            <Text style={s.coverLabel}>Date of Incident</Text>
            <Text style={s.coverValue}>{props.incidentDate}</Text>
          </View>
          <View style={s.coverRow}>
            <Text style={s.coverLabel}>Organisation</Text>
            <Text style={s.coverValue}>{props.orgName}</Text>
          </View>
          {props.orgAddress && (
            <View style={s.coverRow}>
              <Text style={s.coverLabel}>Address</Text>
              <Text style={s.coverValue}>{props.orgAddress}</Text>
            </View>
          )}
          <View style={s.coverRow}>
            <Text style={s.coverLabel}>Status</Text>
            <Text style={[s.coverValue, { color: colors.headerBg }]}>{props.status}</Text>
          </View>
          <View style={s.coverRow}>
            <Text style={s.coverLabel}>Severity</Text>
            <Text style={[s.coverValue, { color: severityColor(props.severity) }]}>{props.severity}</Text>
          </View>
          <View style={s.coverRow}>
            <Text style={s.coverLabel}>Report Date</Text>
            <Text style={s.coverValue}>{props.reportDate}</Text>
          </View>
          <View style={s.coverRow}>
            <Text style={s.coverLabel}>Prepared By</Text>
            <Text style={s.coverValue}>{props.investigatorName || props.reporterName}</Text>
          </View>
        </View>

        <Text style={s.confidentialBanner}>CONFIDENTIAL</Text>

        <PageFooter reportDate={props.reportDate} pageNum="Page 1" />
      </Page>

      {/* ── Page 2: Incident Details ── */}
      <Page size="A4" style={s.page}>
        <Text style={s.formRef}>Investigation Report \u2014 {props.incidentRef}</Text>

        <Section title="A. Basic Details" />
        <Field label="Incident Title" value={props.title} />
        <Field label="Incident Type" value={props.incidentType} />
        <Field label="Date of Incident" value={props.incidentDate} />
        <Field label="Time of Incident" value={props.incidentTime} />
        <Field label="Location" value={props.location} />
        <Field label="Severity" value={props.severity} />
        <Field label="Status" value={props.status} />

        <Section title="B. Personnel Involved" />
        <Field label="Injured / Affected Party" value={props.injuredParty} />
        <Field label="Occupation / Job Title" value={props.victimOccupation} />
        <Field label="Staff / Employee Number" value={props.victimStaffNo} />
        <Field label="Department" value={props.victimDepartment} />
        <Field label="ID / Passport Number" value={props.victimIdNumber} />
        <Field label="Nationality" value={props.victimNationality} />
        <Field label="Contractor (if applicable)" value={props.victimContractor} />
        <Field label="Immediate Supervisor" value={props.immediateSupervisor} />
        <Field label="Date of Birth" value={props.victimDateOfBirth} />

        <Section title="C. Injury & Treatment" />
        <Field label="Nature of Injury" value={props.natureOfInjury} />
        <Field label="Body Part(s) Injured" value={props.bodyPartInjured} />
        <Field label="Treatment Type" value={props.treatmentType} />
        <Field label="Treating Doctor / Practitioner" value={props.treatingDoctor} />
        <Field label="Hospital / Clinic" value={props.hospitalClinic} />
        <Field label="Lost Days" value={props.lostDays} />
        <Field label="Returned to Work" value={props.returnedToWork} />
        <Field label="Date Returned" value={props.returnedToWorkDate} />

        <PageFooter reportDate={props.reportDate} pageNum="Page 2" />
      </Page>

      {/* ── Page 3: Investigation ── */}
      <Page size="A4" style={s.page}>
        <Text style={s.formRef}>Investigation Report \u2014 {props.incidentRef}</Text>

        <Section title="D. Description of Incident" />
        <FullField label="Full Description" value={props.description} />

        <Section title="E. Immediate Action Taken" />
        <FullField label="Actions taken at the scene" value={props.immediateAction} />

        <Section title="F. Root Cause Analysis" />
        {props.rootCauseData ? (
          <View>
            <Field label="Analysis Method" value={props.rootCauseData.method} />
            <Field label="Category" value={props.rootCauseData.category} />
            {props.rootCauseData.whys && props.rootCauseData.whys.length > 0 && (
              <View style={{ marginTop: 6, marginBottom: 6 }}>
                <Text style={{ fontSize: 8, color: colors.gray, marginBottom: 4 }}>5-Whys Chain</Text>
                {props.rootCauseData.whys.map((why, i) => (
                  <View key={i} style={s.whyRow}>
                    <Text style={s.whyLabel}>Why {i + 1}:</Text>
                    <Text style={s.whyText}>{why.answer || why.question}</Text>
                  </View>
                ))}
              </View>
            )}
            <FullField label="Root Cause Conclusion" value={props.rootCauseData.rootCause} />
            <FullField label="Containment Action" value={props.rootCauseData.containmentAction} />
          </View>
        ) : (
          <FullField label="Root Cause" value={props.rootCause} />
        )}

        <Section title="G. Contributing Factors" />
        {props.contributingFactors && props.contributingFactors.length > 0 ? (
          <View style={{ paddingLeft: 8 }}>
            {props.contributingFactors.map((factor, i) => (
              <Text key={i} style={{ fontSize: 8, marginBottom: 2 }}>{"\u2022"} {factor}</Text>
            ))}
          </View>
        ) : (
          <Text style={{ fontSize: 8, color: colors.gray, paddingLeft: 8 }}>No contributing factors recorded.</Text>
        )}

        <PageFooter reportDate={props.reportDate} pageNum="Page 3" />
      </Page>

      {/* ── Page 4: Witnesses & Evidence ── */}
      <Page size="A4" style={s.page}>
        <Text style={s.formRef}>Investigation Report \u2014 {props.incidentRef}</Text>

        <Section title="H. Witness Statements" />
        {props.witnesses && props.witnesses.length > 0 ? (
          props.witnesses.map((w, i) => (
            <View key={i} style={s.witnessCard}>
              <Text style={s.witnessName}>{i + 1}. {w.name}</Text>
              <Text style={s.witnessContact}>
                {[w.contactNumber, w.email].filter(Boolean).join(" | ") || "No contact details"}
              </Text>
              {w.statement && (
                <View>
                  <Text style={{ fontSize: 7, color: colors.gray, marginBottom: 1 }}>Statement:</Text>
                  <Text style={s.witnessStatement}>{w.statement}</Text>
                </View>
              )}
            </View>
          ))
        ) : (
          <Text style={{ fontSize: 8, color: colors.gray, paddingLeft: 8 }}>No witness statements recorded.</Text>
        )}

        <Section title="I. Evidence Files" />
        {props.evidence && props.evidence.length > 0 ? (
          <View>
            <View style={s.tableHeader}>
              <Text style={[s.tableHeaderCell, { width: "40%" }]}>File Name</Text>
              <Text style={[s.tableHeaderCell, { width: "20%" }]}>Type</Text>
              <Text style={[s.tableHeaderCell, { width: "20%" }]}>Uploaded</Text>
              <Text style={[s.tableHeaderCell, { width: "20%" }]}>By</Text>
            </View>
            {props.evidence.map((e, i) => (
              <View key={i} style={s.tableRow}>
                <Text style={[s.tableCell, { width: "40%" }]}>{e.fileName}</Text>
                <Text style={[s.tableCell, { width: "20%" }]}>{e.fileType}</Text>
                <Text style={[s.tableCell, { width: "20%" }]}>{e.uploadedAt}</Text>
                <Text style={[s.tableCell, { width: "20%" }]}>{e.uploadedBy}</Text>
              </View>
            ))}
          </View>
        ) : (
          <Text style={{ fontSize: 8, color: colors.gray, paddingLeft: 8 }}>No evidence files attached.</Text>
        )}

        <PageFooter reportDate={props.reportDate} pageNum="Page 4" />
      </Page>

      {/* ── Page 5: Corrective Actions & Closure ── */}
      <Page size="A4" style={s.page}>
        <Text style={s.formRef}>Investigation Report \u2014 {props.incidentRef}</Text>

        <Section title="J. Linked Corrective / Preventive Actions (CAPA)" />
        {props.linkedCapas && props.linkedCapas.length > 0 ? (
          <View>
            <View style={s.tableHeader}>
              <Text style={[s.tableHeaderCell, { width: "40%" }]}>Title</Text>
              <Text style={[s.tableHeaderCell, { width: "20%" }]}>Type</Text>
              <Text style={[s.tableHeaderCell, { width: "20%" }]}>Priority</Text>
              <Text style={[s.tableHeaderCell, { width: "20%" }]}>Status</Text>
            </View>
            {props.linkedCapas.map((c, i) => (
              <View key={i} style={s.tableRow}>
                <Text style={[s.tableCell, { width: "40%" }]}>{c.title}</Text>
                <Text style={[s.tableCell, { width: "20%" }]}>{c.type}</Text>
                <Text style={[s.tableCell, { width: "20%" }]}>{c.priority}</Text>
                <Text style={[s.tableCell, { width: "20%" }]}>{c.status}</Text>
              </View>
            ))}
          </View>
        ) : (
          <Text style={{ fontSize: 8, color: colors.gray, paddingLeft: 8 }}>No linked CAPA records.</Text>
        )}

        <Section title="K. Regulatory Reporting" />
        <Field label="Reportable Incident" value={props.isReportable ? "Yes" : "No"} />
        <Field label="MHSA Section" value={props.mhsaSection} />
        <Field label="Reporting Deadline" value={props.reportingDeadline} />
        <Field label="Statutory Report Submitted" value={props.statutoryReportedAt} />

        <Section title="L. Estimated Cost & Impact" />
        <Field label="Estimated Cost" value={props.estimatedCost} />
        {props.impactAreas && props.impactAreas.length > 0 ? (
          <View style={s.fieldRow}>
            <Text style={s.fieldLabel}>Impact Areas</Text>
            <Text style={s.fieldValue}>{props.impactAreas.join(", ")}</Text>
          </View>
        ) : (
          <Field label="Impact Areas" value={undefined} />
        )}

        {/* Signatures */}
        <View style={{ marginTop: 24 }}>
          <Section title="M. Signatures" />
          <View style={s.sigRow}>
            <View style={s.sigBlock}>
              <View style={s.sigLine} />
              <Text style={s.sigLabel}>Investigator</Text>
              <Text style={{ fontSize: 8, marginTop: 2 }}>{props.investigatorName || "\u2014"}</Text>
            </View>
            <View style={s.sigBlock}>
              <View style={s.sigLine} />
              <Text style={s.sigLabel}>Reported By</Text>
              <Text style={{ fontSize: 8, marginTop: 2 }}>{props.reporterName}</Text>
            </View>
          </View>
          <View style={[s.sigRow, { marginTop: 10 }]}>
            <View style={s.sigBlock}>
              <View style={s.sigLine} />
              <Text style={s.sigLabel}>Manager / Reviewer</Text>
            </View>
            <View style={s.sigBlock}>
              <View style={s.sigLine} />
              <Text style={s.sigLabel}>Date</Text>
              <Text style={{ fontSize: 8, marginTop: 2 }}>{props.reportDate}</Text>
            </View>
          </View>
        </View>

        <View style={s.notice}>
          <Text>This investigation report is an internal document prepared for safety management purposes.
            It may contain privileged information and should not be disclosed to unauthorised parties.
            Retain in accordance with your organisation&apos;s records retention policy.</Text>
        </View>

        <PageFooter reportDate={props.reportDate} pageNum="Page 5" />
      </Page>
    </Document>
  )
}
